<a href="https://colab.research.google.com/github/Shrinathrajeshirke/deep-learning-churn-prediction/blob/main/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from tensorflow.keras.preprocessing.text import one_hot

In [10]:
### sentences

sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [11]:
## define the vocabulary size
voc_size = 10000

In [12]:
## onehote representation

encoded_docs = [one_hot(words, voc_size) for words in sent]
encoded_docs

[[9476, 5422, 3654, 9347],
 [9476, 5422, 3654, 4427],
 [9476, 6239, 3654, 1363],
 [5558, 3428, 1688, 6304, 8467],
 [5558, 3428, 1688, 6304, 9979],
 [1862, 9476, 6024, 3654, 344],
 [5791, 9665, 8643, 6304]]

In [15]:
### word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [16]:
sent_length = 8
encoded_docs = pad_sequences(encoded_docs, padding='pre', maxlen=sent_length)
print(encoded_docs)

[[   0    0    0    0 9476 5422 3654 9347]
 [   0    0    0    0 9476 5422 3654 4427]
 [   0    0    0    0 9476 6239 3654 1363]
 [   0    0    0 5558 3428 1688 6304 8467]
 [   0    0    0 5558 3428 1688 6304 9979]
 [   0    0    0 1862 9476 6024 3654  344]
 [   0    0    0    0 5791 9665 8643 6304]]


In [17]:
### feature representation

dim = 10

In [23]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(encoded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step


array([[[-0.01539307, -0.01822763,  0.03244719,  0.01746266,
          0.01593428,  0.02135861, -0.03578099, -0.00949006,
         -0.02707946, -0.01334001],
        [-0.01539307, -0.01822763,  0.03244719,  0.01746266,
          0.01593428,  0.02135861, -0.03578099, -0.00949006,
         -0.02707946, -0.01334001],
        [-0.01539307, -0.01822763,  0.03244719,  0.01746266,
          0.01593428,  0.02135861, -0.03578099, -0.00949006,
         -0.02707946, -0.01334001],
        [-0.01539307, -0.01822763,  0.03244719,  0.01746266,
          0.01593428,  0.02135861, -0.03578099, -0.00949006,
         -0.02707946, -0.01334001],
        [ 0.02699289, -0.04843196,  0.01007605, -0.01534132,
          0.02735502, -0.01083184, -0.04812795, -0.00369171,
          0.00245662, -0.00932872],
        [ 0.04365977, -0.04942346,  0.03505066,  0.00703238,
         -0.02505132, -0.04496702,  0.01147699, -0.00162427,
          0.04621829,  0.02996511],
        [ 0.04908412, -0.00223295, -0.01018139,  0.0